rm Hello.aux
rm Hello.log             
rm Hello.out             
rm Hello.synctex.gz      
rm Hello.tmp             
rm Hello.gz              
rm Hello.nav             
rm Hello.synctex         
rm Hello.toc  
